name: W&B runs

on: [issue_comment]

jobs:
  eval:
    if: (github.event.issue.pull_request != null) &&  contains(github.event.comment.body, '/eval')
    runs-on: ubuntu-latest

    steps:
      - name: Get PR SHA
        id: comment
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: "/eval"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.comment.outputs.SHA }}

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Create run
        run: |
          pip install -r requirements.txt
          python evaluate.py 168 --wandb-proj gha
          sleep 10
        env:
          WANDB_SHA: ${{ steps.comment.outputs.SHA }}
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

      - name: Get Runs Using SHA
        uses: machine-learning-apps/wandb-action@master
        id: wandb
        with:
          PROJECT_NAME: ${{ format('{0}/{1}', secrets.WANDB_ENTITY, secrets.WANDB_PROJECT) }}
          FILTER_GITHUB_SHA: ${{ steps.comment.outputs.SHA }}
          BASELINE_TAGS: "['baseline']"
          DISPLAY_METRICS: "['mse', '_runtime']"
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          DEBUG: 'true'

      - name: Upload csv
        if: steps.wandb.outputs.BOOL_COMPLETE == 'true'
        uses: actions/upload-artifact@v1
        with:
          name: wandb_report
          path: wandb_report.csv

      - name: process_data
        if: steps.wandb.outputs.BOOL_COMPLETE == 'true'
        run: |
          cd $GITHUB_WORKSPACE
          pip install tabulate==0.8.5 requests==2.22.0
          python action_files/wandb_results.py
        env:
          PR_NUM: ${{ steps.comment.outputs.PULL_REQUEST_NUMBER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
